exclude: '^.*\.webm$'
repos:
    - repo: https://github.com/biomejs/pre-commit
      rev: 'v0.1.0' # Use the sha / tag you want to point at
      hooks:
          - id: biome-check
            additional_dependencies: ['@biomejs/biome@1.8.3']

    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.56.0
      hooks:
          - id: eslint
            files: \.js$
            types: [file]

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-xml
          - id: check-yaml
          - id: check-json
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-merge-conflict
          - id: check-added-large-files
            args: ['--maxkb=128']
            exclude_types: [png,svg,zip]
          - id: check-case-conflict
          - id: check-shebang-scripts-are-executable
