export const store = {
    tour_technical: true,
    tour_technical_version: 1,
    step_technical_experimentalOption: false,
    step_technical_addWAFallback: false,
    step_technical_removeWAFallback: false,
    step_technical_extensionState: false,
    step_technical_extensionFeaturesConfiguration: false,
    step_technical_extensionConfiguration: false,
};

export const steps = {
    step_technical_experimentalOption: {
        id: 'step_technical_experimentalOption',
        tour: 'tour_technical',
        name: 'Experimental / Advanced',
        description: 'Advanced configuration options for informed user.',
        next: 'step_technical_addWAFallback',
        progression: 20,
    },
    step_technical_addWAFallback: {
        id: 'step_technical_addWAFallback',
        tour: 'tour_technical',
        name: 'Window Actions - No access',
        description: "You don't have the access to see 'Window Action' records? Add model fallback here",
        trigger: [{ selector: '#joorney_window_action_fallback_new_path_save', run: 'click' }],
        next: 'step_technical_removeWAFallback',
        progression: 20,
    },
    step_technical_removeWAFallback: {
        id: 'step_technical_removeWAFallback',
        tour: 'tour_technical',
        name: 'Window Actions - Removal',
        description: "Revoke or adjust the fallback for 'Window Action' records as needed.",
        trigger: [{ selector: '[class^="joorney_window_action_fallback_origin_delete"]', run: 'click' }],
        next: 'step_technical_extensionState',
        progression: 20,
    },
    step_technical_extensionState: {
        id: 'step_technical_extensionState',
        tour: 'tour_technical',
        name: 'Extension State',
        description: 'Review the list of enabled features in the current version/build.',
        trigger: [{ selector: '#joorney-extension-state .expander', run: 'click' }],
        next: 'step_technical_onboardingProgress',
        progression: 15,
    },
    step_technical_onboardingProgress: {
        id: 'step_technical_onboardingProgress',
        tour: 'tour_technical',
        name: 'Onboarding progression',
        description: "Check your onboarding progression stored in Chrome's local storage.",
        trigger: [{ selector: '#joorney-onboarding-progression .expander', run: 'click' }],
        next: 'step_technical_extensionFeaturesConfiguration',
        progression: 15,
    },
    step_technical_extensionFeaturesConfiguration: {
        id: 'step_technical_extensionFeaturesConfiguration',
        tour: 'tour_technical',
        name: 'Feature Setup',
        description: 'Explore configurations for all features.',
        trigger: [{ selector: '#joorney-extension-features .expander', run: 'click' }],
        next: 'step_technical_extensionConfiguration',
        progression: 15,
    },
    step_technical_extensionConfiguration: {
        id: 'step_technical_extensionConfiguration',
        tour: 'tour_technical',
        name: 'User Configuration',
        description: "Check your user configuration stored in Chrome's sync storage.",
        trigger: [{ selector: '#joorney-storage-configuration .expander', run: 'click' }],
        progression: 15,
    },
};
