import { ToastManager } from '../../../src/toast/index.js';
import { StorageSync } from '../../../src/utils/browser.js';
import { sleep } from '../../../src/utils/util.js';

export async function loadPage(features, currentSettings) {
    ToastManager.load();

    handleToastMode(currentSettings.toastMode);
    handleToastType(JSON.parse(currentSettings.toastType));
}

let joorneyCurrentToastMode = undefined;

function handleToastMode(mode) {
    const radioButtons = document.querySelectorAll('.joorney-toast-mode-control input[type="radio"]');
    for (const radio of radioButtons) {
        radio.checked = mode === radio.value;
        if (radio.checked) joorneyCurrentToastMode = mode;
        radio.onchange = (e) => {
            joorneyCurrentToastMode = e.target.value;
            StorageSync.set({ toastMode: joorneyCurrentToastMode });
            ToastManager.load();
        };
    }

    document.getElementById('joorney-toast-mode-showme').onclick = () => showMockToast();
}

function handleToastType(types) {
    const checkboxes = document.querySelectorAll('.joorney-toast-mode-control input[type="checkbox"]');
    for (const checkbox of checkboxes) {
        checkbox.checked = types[checkbox.dataset.toastType];
        checkbox.onchange = (e) => {
            StorageSync.set({
                toastType: JSON.stringify({ ...types, [e.target.dataset.toastType]: e.target.checked }),
            });
            ToastManager.load();
        };
    }
}

async function showMockToast() {
    if (!joorneyCurrentToastMode) return;
    const types = await StorageSync.get('toastType');
    const toastType = JSON.parse(types.toastType);

    if (
        ToastManager.info(
            'options-demo-info',
            'Update Available',
            `A new software update is available for download.

        This update includes several new features and performance improvements.
        It is recommended to install the update as soon as possible.

        Make sure your device is connected to the internet and has sufficient battery life.
        Click on the update button to start the process.
        <br /><br /><small>Generated by ChatGPT.</small>`
        )
    )
        await sleep(500);
    if (
        ToastManager.warn(
            'options-demo-warn',
            'Password Expiring',
            `Your profile has been successfully updated.
            All changes have been saved and are now active.
            You can review your updated profile information in the settings section.
            If you encounter any issues, please contact support.
            Thank you for keeping your information current.
            <br /><br /><small>Generated by ChatGPT.</small>`
        )
    )
        await sleep(500);

    if (
        ToastManager.error(
            'options-demo-error',
            'Connection Lost',
            `Your password will expire in 3 days.
            Please update it to ensure continued access to your account.
            It is recommended to choose a strong and unique password that you haven't used before.
            If you do not update your password, you may be locked out of your account.
             Go to the settings page to change your password.
            <br /><br /><small>Generated by ChatGPT.</small>`
        )
    )
        await sleep(500);

    if (toastType.success) {
        ToastManager.success(
            'options-demo-success',
            'Profile Updated',
            `Unable to connect to the server.
            Please check your internet connection and try again.
            If the problem persists, it might be due to server maintenance or network issues on our end.
            We apologize for the inconvenience.
            You can retry the connection or contact support for further assistance.
            <br /><br /><small>Generated by ChatGPT.</small>`
        );
    }
}
