// TODO MOVE TO lib/enum.ts
export enum MESSAGE_ACTION {
    GET_FEATURES_LIST = 'GET_FEATURES_LIST',
    GET_FINAL_RUNBOT_URL = 'GET_FINAL_RUNBOT_URL',
    UPDATE_EXT_STATUS = 'UPDATE_EXT_STATUS',
}
